#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║   🔧 CORRECTION URL SUPABASE                                  ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "❌ ERREUR ACTUELLE : Tenant or user not found"
echo ""
echo "CAUSE : Le mot de passe dans DATABASE_URL est incorrect"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 ÉTAPES POUR OBTENIR LA BONNE URL :"
echo ""
echo "1️⃣  Allez sur : https://supabase.com"
echo ""
echo "2️⃣  Connectez-vous et sélectionnez votre projet"
echo ""
echo "3️⃣  Cliquez sur ⚙️ Settings (dans la sidebar gauche)"
echo ""
echo "4️⃣  Cliquez sur 🗄️ Database"
echo ""
echo "5️⃣  Descendez jusqu'à 'Connection string'"
echo ""
echo "6️⃣  ✅ COCHEZ 'Use connection pooling'"
echo ""
echo "7️⃣  Sélectionnez 'Transaction' (Port 6543)"
echo ""
echo "8️⃣  Copiez l'URL qui s'affiche"
echo ""
echo "    Format :"
echo "    postgresql://postgres.[PROJECT-REF]:[YOUR-PASSWORD]@aws-X-xxx.pooler.supabase.com:6543/postgres"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  SI VOUS AVEZ OUBLIÉ LE MOT DE PASSE :"
echo ""
echo "1. Dans Settings → Database"
echo "2. Cliquez sur 'Reset Database Password'"
echo "3. Créez un nouveau mot de passe SIMPLE (ex: admin123)"
echo "4. ⚠️  NOTEZ-LE quelque part !"
echo "5. Utilisez ce mot de passe dans l'URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 UNE FOIS L'URL OBTENUE :"
echo ""
echo "Modifiez le fichier .env avec la commande :"
echo ""
echo "nano .env"
echo ""
echo "Remplacez la ligne DATABASE_URL par votre VRAIE URL"
echo ""
echo "Exemple :"
echo "DATABASE_URL=postgresql://postgres.pzzfqduntcmklrakhggy:VotreVraiMotDePasse@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"
echo ""
echo "Sauvegardez : CTRL+O puis ENTER, quittez : CTRL+X"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ PUIS RELANCEZ L'APPLICATION :"
echo ""
echo "python run.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 ASTUCE : Pour un mot de passe simple, utilisez :"
echo ""
echo "   - Pas d'espaces"
echo "   - Pas de caractères spéciaux compliqués"
echo "   - Ex: Admin2024! ou Supabase123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

