"""Ajout colonne taille_cachet_pdf

Revision ID: 19d92f4bd0bf
Revises: f7f39b3674b8
Create Date: 2026-03-09 14:12:53.311131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19d92f4bd0bf'
down_revision = 'f7f39b3674b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificats', schema=None) as batch_op:
        batch_op.alter_column('type_certificat',
               existing_type=postgresql.ENUM('cours', 'module', 'formation', name='type_certificat_enum'),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'cours'::type_certificat_enum"))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_nom_classe'), ['nom_classe'], unique=False)

    with op.batch_alter_table('configuration_ecole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taille_cachet_pdf', sa.Float(), nullable=True))

    with op.batch_alter_table('cours_elearning', schema=None) as batch_op:
        batch_op.alter_column('type_contenu',
               existing_type=postgresql.ENUM('video', 'document', 'quiz', 'exercice', name='type_contenu_enum'),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'video'::type_contenu_enum"))

    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.alter_column('departement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type_diplome',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'fondamental'::character varying"))
        batch_op.drop_constraint(batch_op.f('uq_filiere_code_type'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_filiere_nom_type'), type_='unique')
        batch_op.create_index(batch_op.f('ix_filieres_code_filiere'), ['code_filiere'], unique=False)
        batch_op.create_index(batch_op.f('ix_filieres_cycle'), ['cycle'], unique=False)
        batch_op.create_index(batch_op.f('ix_filieres_nom_filiere'), ['nom_filiere'], unique=False)
        batch_op.create_foreign_key(None, 'departements', ['departement_id'], ['id'])

    with op.batch_alter_table('interactions_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_ia_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('mesures_simulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesures_simulation_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mesures_simulation_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('participants_collaboratifs', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('createur', 'participant', name='role_collab_enum'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'participant'::role_collab_enum"))

    with op.batch_alter_table('questions_quiz', schema=None) as batch_op:
        batch_op.alter_column('type_question',
               existing_type=postgresql.ENUM('qcm_unique', 'qcm_multiple', 'vrai_faux', 'texte_court', name='type_question_enum'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'qcm_unique'::type_question_enum"))

    with op.batch_alter_table('reactions_chimiques', schema=None) as batch_op:
        batch_op.alter_column('type_reaction',
               existing_type=postgresql.ENUM('oxydoreduction', 'acide_base', 'saponification', 'esterification', 'hydrolyse', 'equilibre', name='type_reaction_enum'),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('sessions_collaboratives', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=postgresql.ENUM('ouverte', 'en_cours', 'terminee', name='statut_collab_enum'),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'ouverte'::statut_collab_enum"))

    with op.batch_alter_table('sessions_tp', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=postgresql.ENUM('en_cours', 'terminé', 'évalué', 'rendu', name='statut_session_enum'),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'en_cours'::statut_session_enum"))
        batch_op.create_index(batch_op.f('ix_sessions_tp_etudiant_id'), ['etudiant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_tp_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_tp_tp_id'), ['tp_id'], unique=False)

    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.alter_column('type_simulation',
               existing_type=postgresql.ENUM('buck', 'boost', 'chute_libre', 'rdm_poutre', 'signal_fourier', 'stock_flux', 'transport_routage', 'thermodynamique', 'pile_electrochimique', 'saponification', name='type_sim_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ia_nom',
               existing_type=postgresql.ENUM('ETA', 'ALPHA', 'KAYT', name='ia_nom_enum'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_tps_ue_id'), ['ue_id'], unique=False)

    with op.batch_alter_table('ues', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('semestre',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'fondamentale'::character varying"))
        batch_op.drop_constraint(batch_op.f('ues_classe_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ues_ue_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['classe_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('ue_parent_id')
        batch_op.drop_column('type_ue')
        batch_op.drop_column('type_ue_creation')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('videos_explicatives', schema=None) as batch_op:
        batch_op.alter_column('niveau',
               existing_type=postgresql.ENUM('debutant', 'intermediaire', 'avance', name='niveau_video_enum'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'debutant'::niveau_video_enum"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_explicatives', schema=None) as batch_op:
        batch_op.alter_column('niveau',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('debutant', 'intermediaire', 'avance', name='niveau_video_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'debutant'::niveau_video_enum"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_ue_creation', sa.VARCHAR(length=20), server_default=sa.text("'simple'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_ue', sa.VARCHAR(length=20), server_default=sa.text("'Obligatoire'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ue_parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ues_ue_parent_id_fkey'), 'ues', ['ue_parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ues_classe_id_fkey'), 'classes', ['classe_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('categorie',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'fondamentale'::character varying"))
        batch_op.alter_column('semestre',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tps_ue_id'))
        batch_op.alter_column('ia_nom',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ETA', 'ALPHA', 'KAYT', name='ia_nom_enum'),
               existing_nullable=False)
        batch_op.alter_column('type_simulation',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('buck', 'boost', 'chute_libre', 'rdm_poutre', 'signal_fourier', 'stock_flux', 'transport_routage', 'thermodynamique', 'pile_electrochimique', 'saponification', name='type_sim_enum'),
               existing_nullable=False)

    with op.batch_alter_table('sessions_tp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_tp_tp_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_tp_statut'))
        batch_op.drop_index(batch_op.f('ix_sessions_tp_etudiant_id'))
        batch_op.alter_column('statut',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('en_cours', 'terminé', 'évalué', 'rendu', name='statut_session_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'en_cours'::statut_session_enum"))

    with op.batch_alter_table('sessions_collaboratives', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('ouverte', 'en_cours', 'terminee', name='statut_collab_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'ouverte'::statut_collab_enum"))

    with op.batch_alter_table('reactions_chimiques', schema=None) as batch_op:
        batch_op.alter_column('type_reaction',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('oxydoreduction', 'acide_base', 'saponification', 'esterification', 'hydrolyse', 'equilibre', name='type_reaction_enum'),
               existing_nullable=False)

    with op.batch_alter_table('questions_quiz', schema=None) as batch_op:
        batch_op.alter_column('type_question',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('qcm_unique', 'qcm_multiple', 'vrai_faux', 'texte_court', name='type_question_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'qcm_unique'::type_question_enum"))

    with op.batch_alter_table('participants_collaboratifs', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('createur', 'participant', name='role_collab_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'participant'::role_collab_enum"))

    with op.batch_alter_table('mesures_simulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesures_simulation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mesures_simulation_session_id'))

    with op.batch_alter_table('interactions_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_ia_session_id'))

    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_filieres_nom_filiere'))
        batch_op.drop_index(batch_op.f('ix_filieres_cycle'))
        batch_op.drop_index(batch_op.f('ix_filieres_code_filiere'))
        batch_op.create_unique_constraint(batch_op.f('uq_filiere_nom_type'), ['nom_filiere', 'type_diplome'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_filiere_code_type'), ['code_filiere', 'type_diplome'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('type_diplome',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'fondamental'::character varying"))
        batch_op.alter_column('departement_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cours_elearning', schema=None) as batch_op:
        batch_op.alter_column('type_contenu',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('video', 'document', 'quiz', 'exercice', name='type_contenu_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'video'::type_contenu_enum"))

    with op.batch_alter_table('configuration_ecole', schema=None) as batch_op:
        batch_op.drop_column('taille_cachet_pdf')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_nom_classe'))

    with op.batch_alter_table('certificats', schema=None) as batch_op:
        batch_op.alter_column('type_certificat',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('cours', 'module', 'formation', name='type_certificat_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'cours'::type_certificat_enum"))

    # ### end Alembic commands ###
