"""Initial migration

Revision ID: 6c6a80eea15f
Revises: 
Create Date: 2026-02-13 09:42:24.152039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6a80eea15f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('couleur', sa.String(length=20), nullable=True),
    sa.Column('criteres', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_ecole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_ecole', sa.String(length=200), nullable=True),
    sa.Column('nom_court', sa.String(length=50), nullable=True),
    sa.Column('slogan', sa.String(length=200), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('site_web', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('logo_header_path', sa.String(length=500), nullable=True),
    sa.Column('filigrane_path', sa.String(length=500), nullable=True),
    sa.Column('couleur_primaire', sa.String(length=7), nullable=True),
    sa.Column('couleur_secondaire', sa.String(length=7), nullable=True),
    sa.Column('couleur_accent', sa.String(length=7), nullable=True),
    sa.Column('numero_agrement', sa.String(length=100), nullable=True),
    sa.Column('numero_registre', sa.String(length=100), nullable=True),
    sa.Column('annee_creation', sa.Integer(), nullable=True),
    sa.Column('signature_directeur_path', sa.String(length=500), nullable=True),
    sa.Column('nom_directeur', sa.String(length=200), nullable=True),
    sa.Column('titre_directeur', sa.String(length=100), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_filiere', sa.String(length=100), nullable=False),
    sa.Column('code_filiere', sa.String(length=20), nullable=True),
    sa.Column('cycle', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filieres_code_filiere'), ['code_filiere'], unique=True)
        batch_op.create_index(batch_op.f('ix_filieres_cycle'), ['cycle'], unique=False)
        batch_op.create_index(batch_op.f('ix_filieres_nom_filiere'), ['nom_filiere'], unique=True)

    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('image_couverture', sa.String(length=255), nullable=True),
    sa.Column('fichier_pdf', sa.String(length=255), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions_chimiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type_reaction', sa.Enum('oxydoreduction', 'acide_base', 'saponification', 'esterification', 'hydrolyse', 'equilibre', name='type_reaction_enum'), nullable=False),
    sa.Column('equation', sa.String(length=500), nullable=True),
    sa.Column('reactifs', sa.Text(), nullable=True),
    sa.Column('produits', sa.Text(), nullable=True),
    sa.Column('delta_h', sa.Float(), nullable=True),
    sa.Column('delta_g', sa.Float(), nullable=True),
    sa.Column('constante_equilibre', sa.Float(), nullable=True),
    sa.Column('ordre_reaction', sa.Integer(), nullable=True),
    sa.Column('energie_activation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('annee_academique', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatures_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('code_verification', sa.String(length=50), nullable=False),
    sa.Column('signature_numerique', sa.Text(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('date_signature', sa.DateTime(), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_verification')
    )
    with op.batch_alter_table('signatures_documents', schema=None) as batch_op:
        batch_op.create_index('idx_code_verification', ['code_verification'], unique=False)
        batch_op.create_index('idx_document', ['document_type', 'document_id'], unique=False)

    op.create_table('statistiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_stat', sa.String(length=50), nullable=True),
    sa.Column('cle', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('annonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('visible_etudiants', sa.Boolean(), nullable=True),
    sa.Column('visible_enseignants', sa.Boolean(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campagnes_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=True),
    sa.Column('anonyme_obligatoire', sa.Boolean(), nullable=True),
    sa.Column('questions_ouvertes', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('publiee', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_classe', sa.String(length=100), nullable=False),
    sa.Column('code_classe', sa.String(length=20), nullable=True),
    sa.Column('cycle', sa.String(length=50), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('capacite_max', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_classe')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_nom_classe'), ['nom_classe'], unique=False)

    op.create_table('enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('mot_de_passe_initial', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('historique_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('table_cible', sa.String(length=50), nullable=True),
    sa.Column('id_cible', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('lue', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametres_systeme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.String(length=500), nullable=True),
    sa.Column('type_valeur', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('modifie_par', sa.Integer(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('nom_fichier', sa.String(length=200), nullable=False),
    sa.Column('type_doc', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numero_inscription', sa.String(length=50), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('nationalite', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('situation_matrimoniale', sa.String(length=50), nullable=True),
    sa.Column('contact_urgence', sa.String(length=20), nullable=True),
    sa.Column('nom_pere', sa.String(length=100), nullable=True),
    sa.Column('nom_mere', sa.String(length=100), nullable=True),
    sa.Column('moyenne_bac', sa.Float(), nullable=True),
    sa.Column('serie_bac', sa.String(length=10), nullable=True),
    sa.Column('moyenne_licence', sa.Float(), nullable=True),
    sa.Column('diplome_licence', sa.String(length=100), nullable=True),
    sa.Column('statut_inscription', sa.String(length=20), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('annee_academique', sa.String(length=20), nullable=True),
    sa.Column('evaluation_ia', sa.Text(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_inscription'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rapports_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('campagne_id', sa.Integer(), nullable=True),
    sa.Column('nb_evaluations', sa.Integer(), nullable=True),
    sa.Column('note_moyenne_globale', sa.Float(), nullable=True),
    sa.Column('note_moyenne_pedagogie', sa.Float(), nullable=True),
    sa.Column('note_moyenne_clarte', sa.Float(), nullable=True),
    sa.Column('note_moyenne_disponibilite', sa.Float(), nullable=True),
    sa.Column('note_moyenne_ponctualite', sa.Float(), nullable=True),
    sa.Column('note_moyenne_organisation', sa.Float(), nullable=True),
    sa.Column('evolution_note', sa.Float(), nullable=True),
    sa.Column('rapport_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campagne_id'], ['campagnes_evaluation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('salle', sa.String(length=50), nullable=True),
    sa.Column('couleur', sa.String(length=20), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_ue', sa.String(length=20), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('nom_ue', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('heures', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('type_ue', sa.String(length=20), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_ue')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('date_absence', sa.Date(), nullable=False),
    sa.Column('justifiee', sa.Boolean(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('document_justificatif', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composantes_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('ponderation', sa.Float(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cours_elearning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('type_contenu', sa.Enum('video', 'document', 'quiz', 'exercice', name='type_contenu_enum'), nullable=True),
    sa.Column('url_video', sa.String(length=500), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('fichier_path', sa.String(length=500), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliberations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moyenne_annuelle', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('mention', sa.String(length=50), nullable=True),
    sa.Column('rang', sa.Integer(), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devoirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('consignes', sa.Text(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('fichier_sujet_path', sa.String(length=500), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('date_limite', sa.DateTime(), nullable=False),
    sa.Column('note_sur', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('numero_serie', sa.String(length=50), nullable=True),
    sa.Column('mention', sa.String(length=50), nullable=True),
    sa.Column('date_emission', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id')
    )
    op.create_table('emploi_temps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('jour', sa.String(length=20), nullable=False),
    sa.Column('heure_debut', sa.String(length=10), nullable=False),
    sa.Column('heure_fin', sa.String(length=10), nullable=False),
    sa.Column('salle', sa.String(length=50), nullable=True),
    sa.Column('type_cours', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enseignant_ue',
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enseignant_id', 'ue_id')
    )
    op.create_table('evaluations_enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('pedagogie', sa.Float(), nullable=True),
    sa.Column('clarte', sa.Float(), nullable=True),
    sa.Column('disponibilite', sa.Float(), nullable=True),
    sa.Column('ponctualite', sa.Float(), nullable=True),
    sa.Column('organisation', sa.Float(), nullable=True),
    sa.Column('points_forts', sa.Text(), nullable=True),
    sa.Column('points_amelioration', sa.Text(), nullable=True),
    sa.Column('commentaire_general', sa.Text(), nullable=True),
    sa.Column('note_globale', sa.Float(), nullable=True),
    sa.Column('anonyme', sa.Boolean(), nullable=True),
    sa.Column('date_evaluation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('date_examen', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('salle', sa.String(length=50), nullable=False),
    sa.Column('surveillant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['surveillant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscriptions_ue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('annee_academique', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('type_simulation', sa.Enum('buck', 'boost', 'chute_libre', 'rdm_poutre', 'signal_fourier', 'stock_flux', 'transport_routage', 'thermodynamique', 'pile_electrochimique', 'saponification', name='type_sim_enum'), nullable=False),
    sa.Column('ia_nom', sa.Enum('ETA', 'ALPHA', 'KAYT', name='ia_nom_enum'), nullable=False),
    sa.Column('fichier_sujet', sa.String(length=500), nullable=True),
    sa.Column('fichier_consigne', sa.Text(), nullable=True),
    sa.Column('note_sur', sa.Integer(), nullable=True),
    sa.Column('bareme', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tps_ue_id'), ['ue_id'], unique=False)

    op.create_table('ue_classe',
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ue_id', 'classe_id')
    )
    op.create_table('certificats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('type_certificat', sa.Enum('cours', 'module', 'formation', name='type_certificat_enum'), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('code_verification', sa.String(length=50), nullable=True),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('fichier_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('date_obtention', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours_elearning.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_verification')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('ue_id', sa.Integer(), nullable=False),
    sa.Column('composante_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('session', sa.String(length=20), nullable=True),
    sa.Column('annee_academique', sa.String(length=20), nullable=True),
    sa.Column('date_saisie', sa.DateTime(), nullable=True),
    sa.Column('saisi_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composante_id'], ['composantes_notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('ue_id', sa.Integer(), nullable=True),
    sa.Column('duree_limite_minutes', sa.Integer(), nullable=True),
    sa.Column('note_passage', sa.Float(), nullable=True),
    sa.Column('tentatives_autorisees', sa.Integer(), nullable=True),
    sa.Column('afficher_corrections', sa.Boolean(), nullable=True),
    sa.Column('melanger_questions', sa.Boolean(), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('date_ouverture', sa.DateTime(), nullable=True),
    sa.Column('date_fermeture', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours_elearning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ue_id'], ['ues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rendus_devoirs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devoir_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('fichier_path', sa.String(length=500), nullable=True),
    sa.Column('commentaire_etudiant', sa.Text(), nullable=True),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('en_retard', sa.Boolean(), nullable=True),
    sa.Column('note_obtenue', sa.Float(), nullable=True),
    sa.Column('commentaire_enseignant', sa.Text(), nullable=True),
    sa.Column('date_correction', sa.DateTime(), nullable=True),
    sa.Column('corrige', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['devoir_id'], ['devoirs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions_collaboratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_id', sa.Integer(), nullable=False),
    sa.Column('createur_id', sa.Integer(), nullable=False),
    sa.Column('nom_session', sa.String(length=200), nullable=True),
    sa.Column('code_acces', sa.String(length=10), nullable=True),
    sa.Column('statut', sa.Enum('ouverte', 'en_cours', 'terminee', name='statut_collab_enum'), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('partage_mesures', sa.Boolean(), nullable=True),
    sa.Column('donnees_partagees', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createur_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tp_id'], ['tps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_acces')
    )
    op.create_table('sessions_tp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'terminé', 'évalué', 'rendu', name='statut_session_enum'), nullable=True),
    sa.Column('donnees_simulation', sa.Text(), nullable=True),
    sa.Column('nb_mesures', sa.Integer(), nullable=True),
    sa.Column('fichier_excel', sa.String(length=500), nullable=True),
    sa.Column('fichier_pdf', sa.String(length=500), nullable=True),
    sa.Column('fichier_rapport', sa.String(length=500), nullable=True),
    sa.Column('note_ia', sa.Float(), nullable=True),
    sa.Column('commentaire_ia', sa.Text(), nullable=True),
    sa.Column('criteres_evaluation', sa.Text(), nullable=True),
    sa.Column('note_finale', sa.Float(), nullable=True),
    sa.Column('commentaire_enseignant', sa.Text(), nullable=True),
    sa.Column('validé', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tp_id'], ['tps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions_tp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_tp_etudiant_id'), ['etudiant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_tp_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_tp_tp_id'), ['tp_id'], unique=False)

    op.create_table('videos_explicatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_video', sa.String(length=500), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('type_simulation', sa.String(length=50), nullable=True),
    sa.Column('tp_id', sa.Integer(), nullable=True),
    sa.Column('langue', sa.String(length=10), nullable=True),
    sa.Column('niveau', sa.Enum('debutant', 'intermediaire', 'avance', name='niveau_video_enum'), nullable=True),
    sa.Column('nb_vues', sa.Integer(), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tp_id'], ['tps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges_etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('date_obtention', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_tp.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_etudiant', sa.Text(), nullable=False),
    sa.Column('reponse_ia', sa.Text(), nullable=False),
    sa.Column('contexte_simulation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ia_nom', sa.String(length=20), nullable=True),
    sa.Column('pertinence_question', sa.Integer(), nullable=True),
    sa.Column('aide_apportee', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_tp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_ia_session_id'), ['session_id'], unique=False)

    op.create_table('mesures_simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temps_relatif', sa.Float(), nullable=True),
    sa.Column('parametres', sa.Text(), nullable=True),
    sa.Column('resultats', sa.Text(), nullable=True),
    sa.Column('type_mesure', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_tp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mesures_simulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesures_simulation_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mesures_simulation_timestamp'), ['timestamp'], unique=False)

    op.create_table('participants_collaboratifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_collab_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('createur', 'participant', name='role_collab_enum'), nullable=True),
    sa.Column('date_rejointe', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('nb_mesures_personnelles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_collab_id'], ['sessions_collaboratives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('enonce', sa.Text(), nullable=False),
    sa.Column('type_question', sa.Enum('qcm_unique', 'qcm_multiple', 'vrai_faux', 'texte_court', name='type_question_enum'), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('reponses_correctes', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('explication', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tentatives_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('reponses', sa.Text(), nullable=True),
    sa.Column('note_obtenue', sa.Float(), nullable=True),
    sa.Column('note_totale', sa.Float(), nullable=True),
    sa.Column('pourcentage', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('terminee', sa.Boolean(), nullable=True),
    sa.Column('reussie', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vues_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('date_vue', sa.DateTime(), nullable=True),
    sa.Column('pourcentage_visionne', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos_explicatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vues_videos')
    op.drop_table('tentatives_quiz')
    op.drop_table('questions_quiz')
    op.drop_table('participants_collaboratifs')
    with op.batch_alter_table('mesures_simulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesures_simulation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mesures_simulation_session_id'))

    op.drop_table('mesures_simulation')
    with op.batch_alter_table('interactions_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_ia_session_id'))

    op.drop_table('interactions_ia')
    op.drop_table('badges_etudiants')
    op.drop_table('videos_explicatives')
    with op.batch_alter_table('sessions_tp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_tp_tp_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_tp_statut'))
        batch_op.drop_index(batch_op.f('ix_sessions_tp_etudiant_id'))

    op.drop_table('sessions_tp')
    op.drop_table('sessions_collaboratives')
    op.drop_table('rendus_devoirs')
    op.drop_table('quiz')
    op.drop_table('notes')
    op.drop_table('certificats')
    op.drop_table('ue_classe')
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tps_ue_id'))

    op.drop_table('tps')
    op.drop_table('inscriptions_ue')
    op.drop_table('examens')
    op.drop_table('evaluations_enseignants')
    op.drop_table('enseignant_ue')
    op.drop_table('emploi_temps')
    op.drop_table('diplomes')
    op.drop_table('devoirs')
    op.drop_table('deliberations')
    op.drop_table('cours_elearning')
    op.drop_table('composantes_notes')
    op.drop_table('absences')
    op.drop_table('ues')
    op.drop_table('seances')
    op.drop_table('rapports_evaluation')
    op.drop_table('etudiants')
    op.drop_table('documents')
    op.drop_table('parametres_systeme')
    op.drop_table('notifications')
    op.drop_table('historique_actions')
    op.drop_table('enseignants')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_nom_classe'))

    op.drop_table('classes')
    op.drop_table('campagnes_evaluation')
    op.drop_table('annonces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('statistiques')
    with op.batch_alter_table('signatures_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_document')
        batch_op.drop_index('idx_code_verification')

    op.drop_table('signatures_documents')
    op.drop_table('semestres')
    op.drop_table('reactions_chimiques')
    op.drop_table('livres')
    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filieres_nom_filiere'))
        batch_op.drop_index(batch_op.f('ix_filieres_cycle'))
        batch_op.drop_index(batch_op.f('ix_filieres_code_filiere'))

    op.drop_table('filieres')
    op.drop_table('configuration_ecole')
    op.drop_table('badges')
    # ### end Alembic commands ###
